-- CREATE TABLE MODELO(
--     COD_MOD NUMERIC(3) PRIMARY KEY,
--     NOME VARCHAR(40) NOT NULL
-- );

CREATE TABLE PROPRIETARIO(
    COD_PROP NUMERIC(8) PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    CPF CHAR(11) UNIQUE
);

-- CREATE TABLE VEICULO(
--     PLACA CHAR(7) PRIMARY KEY,
-- 	COR VARCHAR(20),
-- 	ANO_MOD CHAR(4),
-- 	VALOR_SEGURADO NUMERIC(9,2),
-- 	ANO_FAB CHAR(4),
-- 	PROPRIETARIO_COD_PROP NUMERIC(8) REFERENCES PROPRIETARIO(COD_PROP),
-- 	MODELO_COD_MOD NUMERIC(3) REFERENCES MODELO(COD_MOD)
-- );
