CREATE TABLE MODELO (
    COD_MOD NUMERIC(3) PRIMARY KEY,
    NOME VARCHAR(80)
);

CREATE TABLE PROPRIETARIO (
    COD_PROP NUMERIC(8) PRIMARY KEY,
    NOME VARCHAR(110) NOT NULL,
    CPF VARCHAR(11) UNIQUE
);

CREATE TABLE VEICULO (
    PLACA CHAR(7) PRIMARY KEY,
    COR VARCHAR(20),
    MODELO NUMERIC(3) REFERENCES MODELO(COD_MOD),
    PROPRIETARIO NUMERIC(8) REFERENCES PROPRIETARIO (COD_PROP),
    ANO_FAB CHAR(4),
    ANO_MOD CHAR(4),
    VALOR_SEGURADO NUMERIC(9, 2)
);